name: Release Go Binaries

on:
  release:
    types: [created, published]
  workflow_dispatch:

jobs:
  releases-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, windows/amd64, darwin/amd64
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          c=$(git rev-parse --short HEAD); b=$(git name-rev --name-only "$c"); echo -n "version=$c ($b branch)" >> $GITHUB_ENV
          echo "ext=$(uname | tr '[:upper:]' '[:lower:]' | case $(cat) in linux) echo 'so';; darwin) echo 'dylib';; msys*|mingw*|cygwin*) echo 'dll';; esac)" >> $GITHUB_ENV
      - uses: wangyoucao577/go-release-action@v1.38
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.20"
          pre_command: go build -o libr6dissect.${{ env.ext }} -buildmode=c-shared exports/exports.go
          extra_files: LICENSE README.md libr6dissect.h libr6dissect.${{ env.ext }}
          ldflags: "-X 'main.Version=${{ env.version }}'"
