name: Release Go Binaries

on:
  release:
    types: [created, published]

jobs:
  releases-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, windows/amd64, darwin/amd64
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          c=$(git rev-parse --short HEAD); b=$(git name-rev --name-only "$c"); echo -n "version=$c ($b branch)" >> $GITHUB_ENV
      - uses: wangyoucao577/go-release-action@v1.38
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.20"
          extra_files: LICENSE README.md
          ldflags: "-X 'main.Version=${{ env.version }}'"
